### ISSUE TITLE
DEFAULT_CONFIG is required

### ISSUE THREAD

**Issue by aegorx** [scriptex/svg-symbol-sprite#18]
Svgo.config.js must be placed in the config directory regardless of whether -c config is configured

```
let svgoConfig = await loadConfig(DEFAULT_CONFIG);
```

**Comment by scriptex** [comment]
Looks like you're right, @aegorx. I will try to fix this as soon as I can! Thanks for reporting.

**Comment by scriptex** [comment]
@aegorx please install the latest version from NPM (1.0.4) or download the latest version from Github. 
Again, thanks for finding this :)
