### ISSUE TITLE
Remove empty `style` attribute

### ISSUE THREAD

**Issue by scriptex** [scriptex/svg-symbol-sprite#24]
As a continuation of the [previous discussion](https://github.com/scriptex/svg-symbol-sprite/issues/22#issuecomment-1310949613)

**Comment by scriptex** [comment]
Done in https://github.com/scriptex/svg-symbol-sprite/releases/tag/1.4.0
Released and available on NPM.

**Comment by Scriptura** [comment]
It's perfect!
